### ISSUE TITLE
Pico shows content without proper layout after theme installation

### ISSUE THREAD

**Issue by lukaswe** [negrel/hugo-theme-pico#41] opened 2022-03-13 22:43 UTC
I've installed the pico theme and hugo-extended as documented in readme on my archlinux system.
building the example site is successful in terms of error messages:
```
$ hugo server --disableFastRender
Start building sites … 
hugo v0.92.0-B3549403+extended linux/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio

                   | FR | EN  
-------------------+----+-----
  Pages            | 18 | 18  
  Paginator pages  |  0 |  0  
  Non-page files   |  0 |  0  
  Static files     | 39 | 39  
  Processed images |  0 |  0  
  Aliases          |  2 |  1  
  Sitemaps         |  2 |  1  
  Cleaned          |  0 |  0  

Built in 3233 ms
Watching for changes in /home/user/hugo_pico_test/{archetypes,assets,content,package.json,static,themes}
Watching for config changes in /home/user/hugo_pico_test/config.toml
Environment: "development"
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

however the preview in my browser refers to some mis-interpration of css:
Resizing the browser window doesn't change anything. I tried multiple browsers including upload to my webserver.
![image](https://user-images.githubusercontent.com/24406480/158082226-61d0ca40-4f76-4d11-b612-e83248a27a61.png)

**Comment by NullP0interEx** [comment] 2022-05-25 09:57
same here

**Comment by negrel** [comment] 2022-05-27 12:09
Could you provide more information as I'm not able to reproduce the issue. Do you have all the dependencies installed (npm, postcss, ...) ? Are you running a web server or `hugo server` ?

**Comment by NullP0interEx** [comment] 2022-05-27 14:24
Hi,

thanks for the fast response. I start the project with "hugo server".

hugo v0.99.1+extended darwin/amd64 BuildDate=unknown
npm 6.14.17
node v14.19.3

**Comment by NullP0interEx** [comment] 2022-05-27 14:32
Of course, I also ran "./setup.sh" and "./update.sh" before that. I installed the dependencies again by hand. There are no errors in the JS console or network tab of the safari web tools.

<img width="1792" alt="CleanShot 2022-05-27 at 16 30 42@2x" src="https://user-images.githubusercontent.com/8757449/170720221-b91c8cfc-53b1-4fe9-a3b9-9b7a4579bf10.png">

**Comment by negrel** [comment] 2022-05-27 14:55
Could you show the content of the HTML head tag pls ?

**Comment by NullP0interEx** [comment] 2022-05-27 14:57
In the same time, I managed to get the website to display correctly.  I deleted the node_modules folder and called the ./setup.sh script again in the root and /themes/pico subdirectory.

**Comment by negrel** [comment] 2022-05-27 15:03
Great !
I will close the issue. If you did something that is not part of the "Getting started" section of the README pls tell me so I can add it.

**Closed as completed by negrel** 2022-05-27 15:03 UTC

**Comment by lukaswe** [comment] 2022-06-12 18:54
Hello @NullP0interEx , 
thanks for that hint. I was able to get pico running after i ran setup.sh in the pico theme directory.
@negrel I somehow didn't understand form the "Getting Started" secton on https://themes.gohugo.io/themes/hugo-theme-pico/ that this re-run in the theme folder is necessary. 
I think there are two ways to accommodate that:

1. either add a step in the Getting Started section
2. or update the script so that it performs that step automatically.

Or did I miss something in the docu?

However: Thanks, it works now also for me!

**Comment by nxcco** [comment] 2022-10-21 09:01
A workaround for this issue is calling `yarn install` or `npm install` in the _themes/pico_ directory and the _script.sh_ on root level.
